// SPDX-License-Identifier: CC-BY-4.0
//
// dsd-guide.adoc: _DSD implementation guide
//
//
# _DSD (Device Specific Data) Implementation Guide
:author: UEFI ACPI Specification Working Group
:revnumber: 2.0-rc0
:revdate: January 2021
:doctype: book
:sectnums:
:toc: macro

// table of contents
toc::[]

// Introduction
## Introduction

This is the ACPI _DSD Implementation Guide.  This guide and associated
documents provide recommendations on the use of the _DSD (Device Specific
Data) method as defined in the ACPI Specification.  The _DSD method is a
device specific configuration object, intended for firmware and software
engineers implementing _DSD or designing software that will use information
supplied by the method.

The _DSD, as defined by the ACPI Specification, returns a Package, the
first and every odd element of which is a Universal Unique Identifier
(UUID) and every even element of which is a Package (Data Structure),
where each of the UUIDs dictates the format of the Data Structure
immediately following it. The well-known UUIDs to use in the _DSD
output and the Data Structure formats associated with them are also
specified in this document.
 
// document copyright and licensing information
### Copyright and License Information

The _DSD Implementation Guide is
(C) 2021, UEFI Forum ASWG <aswg@uefi.org>.

The _DSD Implementation Guide is licensed under the Creative Commons
Attribution 4.0 International License (CC-BY 4.0).  The full license
text is available at https://creativecommons.org/licenses/by/4.0/.

// changelog for the document
### Change Log

* Version 2.0
** Initial conversion to asciidoc from original v1.2.
** Add in process and naming recommendations.

// define terms
### Terms

The following terms are used in this document:

ACPI:: Advanced Configuration and Power Interface specification.
Device:: Hardware component or set of interrelated hardware registers.
Device ID:: Plug and Play ID or ACPI ID of a device.
GUID:: Globally Unique Identifier. A 128-bit value used to uniquely
   name entities. A unique GUID can be generated by an individual
   without the help of a centralized authority. This allows the
   generation of names that will never conflict, even among multiple,
   unrelated parties.
UUID:: Universal Unique Identifier, a synonym for GUID.

### Conventions

The following typographic connventions are used:

Computer Text:: ``monospace text`` is used to represent computer
   inputs or outputs.
Stress:: *bold text* is used to add emphasis to terms.
Terms:: _italic text_ is used to highlight important terminology.

